version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: zubairriaz78696/udacity-reverseproxy
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: zubairriaz78696/udacity-restapi-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: zubairriaz78696/udacity-restapi-user
  frontend:
    build:
      context: ../../udacity-c3-frontend  
      args:
        - BUILD_ENV=production
    image: zubairriaz78696/udacity-frontend:V2